# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: krcore
canonical: http://www.hl7korea.or.kr/fhir/krcore
version: 0.1.0
name: KRCoreImplementationGuide
title: KRCore Implementation Guide
status: draft
publisher: Jaehoon Lee
contact:
  - name: Jaehoon Lee
    telecom:
      - system: email
        value: jhlee.bmi@gmail.com
description: KRCore Implementation Guide
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2024+
releaseLabel: ci-build
dependencies:
  hl7.terminology.r4:
    version: 5.3.0
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    id: hl7tx
  hl7.fhir.uv.extensions.r4:
    version: 1.0.0
    uri: http://hl7.org/fhir/extensions/ImplementationGuide/hl7.fhir.uv.extensions
    id: hl7ext
  
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Table of Contents: toc.html
  Artifacts Summary: artifacts.html
  Other Resources:
    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
